sudo: true

language: java

script:
  - cd Java && ./gradlew build

jdk: oraclejdk8

notifications:
  email:
    recipients:
      - cade@lnstempunks.org
    on_success: change
    on_failure: change
