sudo: true

language: java

before_install:

  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-setuptools
  - sudo easy_install3 pip
  - pip3 install pyfrc pynetworktables

install:
  - pushd Java
  - ./gradlew build
  - popd
  - pushd Python
  - python3 src/robot.py test

jdk: oraclejdk8
